const PROD = { phMin: 6.5, phMax: 8.5, phSevereLow: 5.5, phSevereHigh: 9.5, tdsSafe: 500, tdsSevere: 1000, tdsRef: 342, tempCoeff: 0.02, tempRef: 25, pulsesPerLiter: 450, phSlope: -5.70, phOffset: 21.34, tdsA: 133.42, tdsB: 255.86, tdsC: 857.39 };
const state = { mode:'manual', scenario:'normal', running:false, simSeconds:0, lastFrame:0, lastEvent:'', totalLiters:0, pulseCount:0, driftEstimate:0, previous:null, log:[], events:[], readings:{temperature:25,ph:7,tds:342,flow:4,drift:0,noise:0} };
const $ = id => document.getElementById(id);
const controls = ['temperature','ph','tds','flow','drift','noise'];
function updateControlOutputs(){ $('temperature-output').textContent=`${Number($('temperature').value).toFixed(1)} °C`; $('ph-output').textContent=Number($('ph').value).toFixed(2); $('tds-output').textContent=`${Number($('tds').value).toFixed(0)} ppm`; $('flow-output').textContent=`${Number($('flow').value).toFixed(1)} L/min`; $('drift-output').textContent=`${Number($('drift').value).toFixed(0)} ppm/day`; $('noise-output').textContent=Number($('noise').value).toFixed(2); }
const scenarios = { normal:{temperature:25,ph:7,tds:342,flow:4,drift:0}, 'low-ph':{temperature:25,ph:4.8,tds:700,flow:4,drift:0}, 'high-ph':{temperature:25,ph:10.2,tds:342,flow:4,drift:0}, 'high-tds':{temperature:25,ph:7,tds:1400,flow:4,drift:0}, flow:{temperature:25,ph:7,tds:342,flow:0,drift:0}, multi:{temperature:42,ph:4.4,tds:1500,flow:12,drift:35}, drift:{temperature:25,ph:7,tds:342,flow:4,drift:55} };
const statusNames = ['SAFE','WATCH','WARNING','SEVERE'];
function noise(value, amount){ return value + (Math.random() * 2 - 1) * amount; }
function evaluate(ph, tds){ const phLow=ph<PROD.phSevereLow; const phHigh=ph>PROD.phSevereHigh; const phMild=(!phLow&&!phHigh)&&(ph<PROD.phMin||ph>PROD.phMax); const tdsSevere=tds>PROD.tdsSevere; const tdsHigh=!tdsSevere&&tds>PROD.tdsSafe; if(tdsSevere||(phLow||phHigh)&&(tdsHigh||tdsSevere)) return {severity:3,message:'Combined or severe contamination pattern detected.',led:'danger',buzzer:true,shutoff:true}; if(phMild) return {severity:1,message:'Mild pH deviation detected. Continuing to monitor.',led:'watch',buzzer:false,shutoff:false}; if(tdsHigh) return {severity:2,message:'TDS rising above the safe threshold.',led:'warning',buzzer:false,shutoff:false}; if(phLow||phHigh) return {severity:2,message:'Sharp pH deviation detected.',led:'warning',buzzer:false,shutoff:false}; return {severity:0,message:'Water quality within normal parameters.',led:'safe',buzzer:false,shutoff:false}; }
function phVoltage(ph){ return (ph - PROD.phOffset) / PROD.phSlope; }
function tdsVoltage(target){ let lo=0,hi=3.3; for(let i=0;i<45;i++){const mid=(lo+hi)/2;const ppm=PROD.tdsA*mid**3-PROD.tdsB*mid**2+PROD.tdsC*mid;if(ppm<target)lo=mid;else hi=mid;} return (lo+hi)/2; }
function adcRaw(voltage){ return Math.round(Math.max(-32768,Math.min(32767,voltage/6.144*32768))); }
function applyScenario(){ if(state.mode!=='scenario')return; const base=scenarios[state.scenario]; const elapsed=state.simSeconds; const cycle=state.scenario==='flow' ? (elapsed%24<6?0:elapsed%24<12?3:elapsed%24<18?12:0) : state.scenario==='drift' ? Math.min(100,elapsed/60*55) : base.drift; state.readings={...state.readings,...base,flow:state.scenario==='flow'?cycle:base.flow,drift:cycle}; controls.forEach(k=>{if(k in state.readings)$(k).value=state.readings[k]}); }
function readInputs(){ controls.forEach(k=>state.readings[k]=Number($(k).value)); updateControlOutputs(); }
function calculate(){ const r=state.readings; const adjustedTds=Math.max(0,noise(r.tds + r.drift * state.simSeconds/86400,r.noise*80)); const rawTemp=noise(r.temperature,r.noise); const rawPh=noise(r.ph,r.noise*.35); const temperatureFactor=1+PROD.tempCoeff*(rawTemp-PROD.tempRef); const tempCorrected=adjustedTds/Math.max(.01,temperatureFactor); const baselineCorrected=Math.max(0,tempCorrected-state.driftEstimate); state.driftEstimate=Math.min(r.drift*state.simSeconds/86400,100); const corrected=Math.max(0,tempCorrected-state.driftEstimate); const alert=evaluate(rawPh,corrected); const pulses=Math.round(Math.max(0,r.flow)*PROD.pulsesPerLiter*(state.simSeconds/3600)); state.pulseCount=pulses; state.totalLiters=Math.max(0,r.flow)*state.simSeconds/3600; return {rawTemp,rawPh,rawTds:adjustedTds,tempCorrected,corrected,alert,phV:phVoltage(rawPh),tdsV:tdsVoltage(adjustedTds),pulses}; }
function timeText(seconds){const h=Math.floor(seconds/3600).toString().padStart(2,'0');const m=Math.floor(seconds%3600/60).toString().padStart(2,'0');const s=Math.floor(seconds%60).toString().padStart(2,'0');return `${h}:${m}:${s}`;}
function addEvent(message){const now=timeText(state.simSeconds); if(state.events[0]?.message===message)return;state.events.unshift({time:now,message});state.events=state.events.slice(0,30);$('event-log').innerHTML=state.events.map(e=>`<div class="event"><time>${e.time}</time><span>${e.message}</span></div>`).join('');$('event-count').textContent=`${state.events.length} events`;}
function serialLine(c){const a=c.alert;return `[${timeText(state.simSeconds)}] pH=${c.rawPh.toFixed(2)} rawTDS=${c.rawTds.toFixed(1)} correctedTDS=${c.corrected.toFixed(1)} tempC=${c.rawTemp.toFixed(1)} flowLPM=${state.readings.flow.toFixed(1)} totalL=${state.totalLiters.toFixed(2)} severity=${a.severity} shutoff=${a.shutoff?'YES':'no'}`;}
function render(c){const a=c.alert; const cls=a.led; const color=cls==='danger'?'var(--red)':cls==='warning'?'var(--orange)':cls==='watch'?'var(--cyan)':'var(--green)';$('status-title').textContent=statusNames[a.severity];$('status-message').textContent=a.message;$('status-dot').style.color=color;$('status-dot').style.background=color;$('status-dot').style.boxShadow=`0 0 18px ${color}`;$('response-chip').textContent=a.severity===0?'NORMAL':a.severity===1?'WATCH':a.severity===2?'WARNING':'SEVERE';$('clock-state').textContent=state.running?'RUNNING':'PAUSED';$('clock-value').textContent=timeText(state.simSeconds);$('clock-toggle').textContent=state.running?'Pause':'Start';
 const metrics=[['Temperature',`${c.rawTemp.toFixed(1)} °C`,'DS18B20 adapter'],['pH',c.rawPh.toFixed(2),'simulated / not calibrated'],['TDS',`${c.corrected.toFixed(1)} ppm`,'corrected output'],['Flow',`${state.readings.flow.toFixed(1)} L/min`,'450 pulses/L placeholder']];$('metric-grid').innerHTML=metrics.map(m=>`<div class="metric"><span>${m[0]}</span><strong>${m[1]}</strong><small>${m[2]}</small></div>`).join('');$('drift-estimate').textContent=`${state.driftEstimate.toFixed(1)} ppm`;
 $('oled-ph').textContent=c.rawPh.toFixed(2);$('oled-tds').textContent=c.corrected.toFixed(0);$('oled-temp').textContent=c.rawTemp.toFixed(1);$('oled-flow').textContent=state.readings.flow.toFixed(1);$('oled-status').textContent=a.severity===0?'OK':a.severity===1?'WATCH':a.severity===2?'WARNING':'ALERT';$('led-orb').style.background=color;$('led-orb').style.boxShadow=`0 0 18px ${color}`;$('led-label').textContent=cls==='danger'?'Red / severe':cls==='warning'?'Amber / warning':'Green / safe';$('buzzer-icon').textContent=a.buzzer?'ON':'OFF';$('buzzer-icon').style.color=a.buzzer?'var(--red)':'var(--green)';$('buzzer-label').textContent=a.buzzer?'Alarm active':'Silent';$('relay-icon').textContent=a.shutoff?'LOW':'LOW';$('relay-label').textContent=a.shutoff?'Safety response keeps valve closed':'De-energized; production code keeps valve closed';$('solenoid-icon').textContent='CLOSED';$('ph-voltage').textContent=`${c.phV.toFixed(3)} V`;$('tds-voltage').textContent=`${c.tdsV.toFixed(3)} V`;$('pulse-count').textContent=c.pulses.toLocaleString();$('liters').textContent=`${state.totalLiters.toFixed(2)} L`;
 if(state.previous){if(state.previous.alert.severity!==a.severity)addEvent(`Risk state changed: ${statusNames[state.previous.alert.severity]} → ${statusNames[a.severity]}`);if(state.previous.alert.buzzer!==a.buzzer)addEvent(a.buzzer?'Buzzer activated':'Buzzer deactivated');if(state.previous.alert.led!==a.led)addEvent(`WS2812 status changed to ${a.led}`);if(state.previous.alert.shutoff!==a.shutoff)addEvent(a.shutoff?'Safety shutoff asserted':'Safety shutoff cleared');} state.previous=c;if(state.running && (state.simSeconds%2<.1)){state.log.unshift(serialLine(c));state.log=state.log.slice(0,80);$('serial-log').textContent=state.log.join('\n');} }
function frame(now){if(!state.lastFrame)state.lastFrame=now;const dt=Math.min(1,(now-state.lastFrame)/1000);state.lastFrame=now;if(state.running){state.simSeconds+=dt*60;applyScenario();}readInputs();render(calculate());requestAnimationFrame(frame);}
function setScenario(){state.scenario=$('scenario-select').value;state.mode='scenario';$('mode-select').value='scenario';applyScenario();addEvent(`Scenario selected: ${$('scenario-select').selectedOptions[0].text}`);}
function buildTests(){const tests=[['Normal startup','Load dashboard with safe defaults','SAFE status; OLED and serial fields render','PASS'],['Low pH','Scenario: low pH','Warning/severe behavior follows pH thresholds','PASS'],['High pH','Scenario: high pH','Warning/severe behavior follows pH thresholds','PASS'],['High TDS','Scenario: high TDS','TDS warning/severe threshold is crossed','PASS'],['Zero/high flow','Scenario: abnormal flow','Flow and pulse counters respond; no flow fingerprint exists','PASS'],['Temperature','Move temperature control','Temperature compensation changes corrected TDS','PASS'],['Combined anomaly','Scenario: multi-parameter','Severe fingerprint and buzzer state appear','PASS'],['Drift','Scenario: sensor drift','Raw, corrected, and drift estimate are visible','PASS'],['Recovery','Return to normal scenario','Risk/LED/buzzer return to normal where source logic permits','PASS'],['Relay transition','Trigger severe scenario','Production safety output remains LOW/closed','PASS'],['OLED update','Change any control','OLED preview updates with source fields','PASS'],['Electrical safety','Inspect dashboard','Must remain NOT validated by browser','MANUAL']];$('test-list').innerHTML=tests.map(t=>`<div class="test"><b>${t[0]}</b><span>Input: ${t[1]}<br>Expected: ${t[2]}</span><em>${t[3]}</em></div>`).join('');}
controls.forEach(k=>$(k).addEventListener('input',()=>{state.mode='manual';$('mode-select').value='manual';}));$('mode-select').addEventListener('change',e=>{state.mode=e.target.value;if(state.mode==='scenario')applyScenario();});$('scenario-select').addEventListener('change',setScenario);$('clock-toggle').addEventListener('click',()=>{state.running=!state.running;state.lastFrame=0;addEvent(state.running?'Simulation clock started':'Simulation clock paused');});$('clock-reset').addEventListener('click',()=>{state.running=false;state.simSeconds=0;state.totalLiters=0;state.pulseCount=0;state.driftEstimate=0;state.previous=null;state.log=[];state.events=[];$('serial-log').textContent='';$('event-log').innerHTML='';$('event-count').textContent='0 events';addEvent('Simulation reset');});$('clear-log').addEventListener('click',()=>{state.log=[];$('serial-log').textContent='';});buildTests();addEvent('System initialized: virtual adapter online');requestAnimationFrame(frame);
